export const bgDarkColorArray = [
    "#0D1B2A", // Deep Indigo/Navy Blue (A professional and calm dark blue)
    "#1A1A1A", // Rich Black/Off-Black (A standard, soft charcoal black)
    "#264653", // Dark Teal (A rich, earthy blue-green)
    "#3A015C", // Deep Eggplant/Violet (A luxurious, dark purple)
    "#4A2C2A", // Dark Burgundy/Brown (A warm, sophisticated dark red-brown)
    "#1C361C", // Dark Forest Green (A muted, deep natural green)
    "#0B0D17", // Dark Navy/Cosmic (A very dark, slightly blue-tinted black)
    "#2E4057", // Dark Slate Blue (A cool, muted blue-gray)
    "#424242", // Dark Gray (A standard Material Design dark gray)
    "#5D5A5A", // Dark Stone Gray (A bit lighter, offering a soft contrast)
    "#394A5C", // Deep Steel Blue (A serious, muted blue)
    "#581845", // Dark Raspberry/Wine (A vibrant, yet deep purple-red)
    "#1B4F72", // Cadet Blue (A dignified, deep grayish-blue)
    "#083D39", // Deep Emerald/Pine Green (A very dark teal-green)
    "#2C3E50", // Midnight Blue (A common, classic dark shade, softer than black)
    "#440A0A", // Dark Mahogany/Maroon (A deep, powerful red-brown)
    "#404040", // Dim Charcoal (A slightly warmer, neutral dark gray)
    "#311B92", // Deep Indigo/Purple (A rich, darker purple shade from Material Design)
    "#004D40", // Dark Green Teal (A dense, forest-like blue-green)
    "#4B3621"  // Dark Espresso/Seal Brown (A deep, warm, earthy brown)
]